// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfagfnpgcbptjiwwoxca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmYWdmbnBnY2JwdGppd3dveGNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNDkzMDMsImV4cCI6MjA1ODgyNTMwM30.4wEx7kqVnb_qY5V_2fmlYntGecNtrAszi2-k5cgG0nQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);